### PR TITLE
add Wrappers for all Impl types and extend Test

### PR DESCRIPTION
**Pull request by jupahe64**
to use more WGPU features (vertexBuffers and uniforms)
also make it more appealing and interesting.

**About this PR**
All structs that end with "Impl" now have their own wrapper class, which implements/exposes all their functions in a very c#ish way
like instead of pointers you pass in arrays or in some cases nullables.

You never have to worry about stuff like Impl, Pointers, Chains, UserData and to some extend descriptors.

I have not yet tested everything but I'm pretty confident that my code works reliably.
But to make sure I have more "coverage" I extended the test so it uses more features like vertexBuffers and uniforms.

This is what it looks like right now:
Triangle Window

it even animates

### CODE REVIEW

**Comment by Trivaxy** [comment]
Hey! Sorry for the late reply - been busy.

A lot of the work here is really promising, but WGPU.NET is meant to be **raw** bindings that allows people to build their _own_ abstractions. Bundling in our own would defeat that purpose.

This is a pretty big change and I wish you could've mentioned it at first before making a surprise pull request 😛 

Regardless, your wrappers are definitely very useful and so is the extensive testing you're providing. I think the wrappers can definitely work as a separate library that depends on WGPU.NET. What do you think?

**Comment by jupahe64** [comment]
The thing is, unlike APIs like opengl WGPU is actually meant to be object oriented, wgpu-native is just a compromise because c interop and c in general doesn't support objects. I just tried to give users an authentic WGPU development experience with what I would say very minimal abstractions to make it object oriented again AND get rid of pointers for I think very obvious reasons.

I don't think there are alot of people who are interested in JUST the raw bindings and if they are they can simply copy WGPU.cs
or generate their own because those people probably know how.

This pull request started when I played around with WGPU.Test and realized that I could read basically none of it, I got the gist but it was very annoying to "unpack" the WGPU struct chains and read through all the struct, pointer, reference mess.
It's just not a good starting point (and it will be the starting point cause most people will search for WGPU .Net + it links to this repo on the wgpu-native repo).
+all other language bindings (I am aware of) use wrapper classes or something like that

About the extra maintenance, I see where you are coming from especially since the spec is work in progress and could change at any time but since the wrappers in most cases directly call the API, it should be fairly easy to identify mismatches and fix them, even if that delays this repo being up to date by 1 day or so I think that's worth it and I would gladly take the role of updating all wrappers when WGPU.cs get's updated.

But if easy of use is not your aim with this project and you really just want it to be raw bindings, then yes I guess I could make my own repository, it just makes things needlessly complicated imo.

**Comment by Trivaxy** [comment]
> The thing is, unlike APIs like opengl WGPU is actually meant to be object oriented, wgpu-native is just a compromise because c interop and c in general doesn't support objects. I just tried to give users an authentic WGPU development experience with what I would say very minimal abstractions to make it object oriented again AND get rid of pointers for I think very obvious reasons.

It's not *really* object-oriented in the same sense that languages like C# or Java demand, but I can see what you mean. It's nice for data and functionality to be bundled well. 

> I don't think there are alot of people who are interested in JUST the raw bindings and if they are they can simply copy WGPU.cs or generate their own because those people probably know how.

They are free to do so! I would've expected other people to have made bindings by now if it were that easy though, I was surprised to find none.

> This pull request started when I played around with WGPU.Test and realized that I could read basically none of it, I got the gist but it was very annoying to "unpack" the WGPU struct chains and read through all the struct, pointer, reference mess.
It's just not a good starting point (and it will be the starting point cause most people will search for WGPU .Net + it links to this repo on the wgpu-native repo).

You're right - it's pretty unpleasant to read in C# at least (hence why people build their abstractions). The current test is actually an almost direct mirror of the C test available in the wgpu-native repository.

> all other language bindings (I am aware of) use wrapper classes or something like that

Assuming you mean the other language bindings for wgpu-native, some of them do while some of them don't - for example, the D and Julia language bindings are almost 1-to-1 interfaces with wgpu-native in the same sense WGPU.NET is with no wrapper utilities of the sort.

> About the extra maintenance, I see where you are coming from especially since the spec is work in progress and could change at any time but since the wrappers in most cases directly call the API, it should be fairly easy to identify mismatches and fix them, even if that delays this repo being up to date by 1 day or so I think that's worth it and I would gladly take the role of updating all wrappers when WGPU.cs get's updated.

It probably would be easy, indeed. I'm also available to update them if needed, which brings me to my last point: I failed to take into consideration that WGPU.NET is the library most people will land on when they try to find bindings for .NET, and looking back, I think you're right in that it is likely not many people are interested in fiddling with the raw internals and dealing with pointer messes.

We can give wrappers a shot by including them alongside the raw bindings, so people can opt to build their own abstractions or use the default ones you are trying to provide. It might be seen by some as library bloat but it's very minimal and can still be stripped out by people that don't want it (even us, if we want to).

What do you think? If you approve, I'll review the PR when I have time.

**Comment by jupahe64** [comment]
I 100% approve, there is no reason to hide the raw API from the library users but adding the wrappers would definitely help people getting started or productive at all and if they don’t like them they don’t have to use them

**Comment by Trivaxy** [comment]
Wow. Sorry for being gone a whole month - life decides not to play nice sometimes.
Anyways, I've skimmed through your commits and I think I'm pleased with most of them 👍 

I'll merge your changes, commit a few things of my own as a bit of cleanup and update WGPU.NET on NuGet soon (ideally once the next version of wgpu-native drops)

**Pull request merged**
